version: "3.2"

services:
  api:
    build:
      context: ..
      dockerfile: building_hack/backend/Dockerfile
    environment:
      PORT: 8000
      FLASK_DEBUG: 0
      PROJECT_NAME: "backend"
    ports:
      - '8000:8000'
    command: uvicorn backend.app.main:app --host 0.0.0.0
    volumes:
      - .:/app

  postgres:
    image: postgres:14.1
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: hack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    restart: always
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"
  frontend:
    build:
      context: ..
      dockerfile: building_hack/frontend/Dockerfile
    ports:
      - '80:3000'
    command: npm start
