version: "3.2"

services:
  api:
    build:
      context: ..
      dockerfile: building_hack/backend/Dockerfile
#    container_name: fastapi-application
    environment:
      PORT: 8000
      FLASK_DEBUG: 1
      PROJECT_NAME: "backend"
    ports:
      - '8000:8000'
    command: uvicorn backend.app.main:app --host 0.0.0.0
    volumes:
      - .:/app


#    ports:
#      - "8000:8000"
#    build:
#      context: ..
#      dockerfile: building_hack/backend/Dockerfile
#    environment:
#      FLASK_DEBUG: 1
#    command: uvicorn app.main:app, --proxy-headers --host 0.0.0.0 --port 80


  postgres:
    image: postgres:14.1
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: hack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    restart: always
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"